name: synvsano
channels:
  - https://conda.anaconda.org/gurobi
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - graphviz
  - conda-forge::python-graphviz
  - pip:
      - absl-py==2.1.0
      - accelerate==0.32.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - arfpy==0.1.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autograd==1.6.2
      - autograd-gamma==0.5.0
      - be-great==0.0.7
      - blis==0.7.11
      - brotli==1.1.0
      - catalogue==2.0.10
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.18.1
      - cloudpickle==3.0.0
      - colorlog==6.8.2
      - confection==0.1.5
      - contourpy==1.2.1
      - ctgan==0.10.1
      - cycler==0.12.1
      - cymem==2.0.8
      - datasets==2.20.0
      - decaf-synthetic-data==0.1.6
      - dill==0.3.8
      - faker==26.0.0
      - fastai==2.7.15
      - fastcore==1.5.51
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - feather-format==0.4.1
      - fflows==0.0.3
      - filelock==3.15.4
      - folktables==0.0.12
      - fonttools==4.53.1
      - formulaic==1.0.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - future==1.0.0
      - geomloss==0.2.6
      - greenlet==3.0.3
      - grpcio==1.65.0
      - gurobipy==11.0.0
      - h5py==3.11.0
      - haversine==2.8.1
      - huggingface-hub==0.23.4
      - idna==3.7
      - imbalanced-learn==0.12.3
      - importlib-metadata==8.0.0
      - inflate64==1.0.0
      - interface-meta==1.3.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - keopscore==2.2.3
      - kiwisolver==1.4.5
      - langcodes==3.4.0
      - language-data==1.2.0
      - lifelines==0.27.7
      - lightning-utilities==0.11.3.post0
      - line-profiler==4.1.3
      - line-profiler-pycharm==1.1.0
      - llvmlite==0.43.0
      - loguru==0.7.2
      - mako==1.3.5
      - marisa-trie==1.2.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - monai==1.3.2
      - multidict==6.0.5
      - multiprocess==0.70.16
      - multivolumefile==0.2.3
      - murmurhash==1.0.10
      - networkx==2.8.8
      - nflows==0.14
      - numba==0.60.0
      - numpy==1.23.5
      - opacus==1.4.0
      - opt-einsum==3.3.0
      - optuna==3.6.1
      - pandas==1.5.3
      - patsy==0.5.6
      - pgmpy==0.1.25
      - pillow==10.4.0
      - ply==3.11
      - preshed==3.0.9
      - protobuf==4.25.3
      - py7zr==0.21.1
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pybcj==1.0.2
      - pybind11==2.13.1
      - pycox==0.2.3
      - pycryptodomex==3.20.0
      - pydantic==1.10.17
      - pykeops==2.2.3
      - pyomo==6.7.3
      - pyparsing==3.1.2
      - pyppmd==1.1.0
      - pytorch-lightning==1.9.5
      - pyts==0.13.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzstd==0.16.0
      - rdt==1.12.2
      - redis==5.0.7
      - regex==2024.5.15
      - requests==2.32.3
      - rich==13.7.1
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - shap==0.46.0
      - shellingham==1.5.4
      - six==1.16.0
      - slicer==0.0.8
      - smart-open==7.0.4
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.31
      - srsly==2.4.8
      - statsmodels==0.14.2
      - synthcity==0.2.10
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - texttable==1.7.0
      - thinc==8.2.5
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torchmetrics==1.4.0.post0
      - torchtext==0.14.1
      - torchtuples==0.2.2
      - tqdm==4.66.4
      - transformers==4.42.3
      - tsai==0.3.9
      - typer==0.12.3
      - urllib3==2.2.2
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.0.3
      - xgboost==1.7.6
      - xgbse==0.2.3
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.19.2
